name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        runs-on: ["windows-latest"]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Install Scoop
        uses: MinoruSekine/setup-scoop@main
      - name: Install JWT UI
        shell: pwsh
        run: |
          scoop bucket add jwt-ui-bucket https://github.com/jwt-rs/scoop-jwt-ui
          scoop install jwt-ui
          jwtui -h
